exports.achieve = function(){

    // Achievements are automatically inserted into each user. Separated from userModel for clarity.

    const achievements = {
        one: {
            name: "First Goal Set",
            image: "/img/achievements/general/set/1-general-set.png",
            type: "general",
            achieved: "unachieved",
            dateAchieved: "null",
            description: "You've set your first goal. 'A journey of a thousand miles begins with a single step.' - Laozi, legendary Chinese philosopher.",
        },
        two: {
            name: "10 Goals Set",
            image: "/img/achievements/general/set/10-general-set.png",
            type: "general",
            achieved: "unachieved",
            dateAchieved: "null",
            description: "10 goals set, keep up the great work!",
        },
        three: {
            name: "20 Goals Set",
            image: "/img/achievements/general/set/20-general-set.png",
            type: "general",
            achieved: "unachieved",
            dateAchieved: "null",
            description: "Wow, 20 goals? Now lets get them completed.",
        },
        four: {
            name: "First Goal Complete",
            image: "/img/achievements/general/complete/1-general-complete.png",
            type: "general",
            achieved: "unachieved",
            dateAchieved: "null",
            description: "Congrats, you've completed your first goal.",
        },
        five: {
            name: "10 Goals Completed",
            image: "/img/achievements/general/complete/10-general-complete.png",
            type: "general",
            achieved: "unachieved",
            dateAchieved: "null",
            description: "10 goals down, got another 10 in you?",
        },
        six: {
            name: "20 Goals Completed",
            image: "/img/achievements/general/complete/20-general-complete.png",
            type: "general",
            achieved: "unachieved",
            dateAchieved: "null",
            description: "Excellent work, 20 goals completed.",
        },
        seven: {
            name: "First Fitness Goal Set",
            image: "/img/achievements/fitness/set/1-fitness-set.png",
            type: "fitness",
            achieved: "unachieved",
            dateAchieved: "null",
            description: "That first fitness goal is always the hardest, let's show it who's boss.",
        },
        eight: {
            name: "10 Fitness Goals Set",
            image: "/img/achievements/fitness/set/10-fitness-set.png",
            type: "fitness",
            achieved: "unachieved",
            dateAchieved: "null",
            description: "Nice, 10 fitness goals set!",
        },
        nine: {
            name: "20 Fitness Goals Set",
            image: "/img/achievements/fitness/set/20-fitness-set.png",
            type: "fitness",
            achieved: "unachieved",
            dateAchieved: "null",
            description: "Oh wow, 20 fitness goals set.",
        },
        ten: {
            name: "First Fitness Goal Completed",
            image: "/img/achievements/fitness/complete/1-fitness-complete.png",
            type: "fitness",
            achieved: "unachieved",
            dateAchieved: "null",
            description: "Exercise is good for the soul, 1 fitness goal complete.",
        },
        eleven: {
            name: "10 Fitness Goals Completed",
            image: "/img/achievements/fitness/complete/10-fitness-complete.png",
            type: "fitness",
            achieved: "unachieved",
            dateAchieved: "null",
            description: "10 fitness goals completed. You got this!",
        },
        twelve: {
            name: "20 Fitness Goals Completed",
            image: "/img/achievements/fitness/complete/20-fitness-complete.png",
            type: "fitness",
            achieved: "unachieved",
            dateAchieved: "null",
            description: "Fitness is your passion. 20 fitness goals completed. Don't stop here though.",
        },
        thirteen: {
            name: "First Healthy-Living Goal Set",
            image: "/img/achievements/health/set/1-health-set.png",
            type: "healthy-living",
            achieved: "unachieved",
            dateAchieved: "null",
            description: "You've set your first healthy-living goal.",
        },
        fourteen: {
            name: "10 Healthy-Living Goals Set",
            image: "/img/achievements/health/set/10-health-set.png",
            type: "healthy-living",
            achieved: "unachieved",
            dateAchieved: "null",
            description: "10 healthy-living goals set.",
        },
        fifteen: {
            name: "20 Healthy Living Goals Set",
            image: "/img/achievements/health/set/10-health-set.png",
            type: "healthy-living",
            achieved: "unachieved",
            dateAchieved: "null",
            description: "How many? 20 healthy living goals set!",
        },
        sixteen: {
            name: "First Healthy-Living Goal Completed",
            image: "/img/achievements/health/complete/1-health-complete.png",
            type: "healthy-living",
            achieved: "unachieved",
            dateAchieved: "null",
            description: "You've done it, first healthy-living goal completed.",
        },
        seventeen: {
            name: "10 Healthy-Living Goals Completed",
            image: "/img/achievements/health/complete/10-health-complete.png",
            type: "healthy-living",
            achieved: "unachieved",
            dateAchieved: "null",
            description: "You've completed 20 healthy-living goals. You must feel great.",
        },
        eighteen: {
            name: "20 Healthy-Living Goals Completed",
            image: "/img/achievements/health/complete/20-health-complete.png",
            type: "healthy-living",
            achieved: "unachieved",
            dateAchieved: "null",
            description: "20 healthy-living goals smashed. What a champ!",
        },
        nineteen: {
            name: "First Nutrition Goal Set",
            image: "/img/achievements/nutrition/set/1-nutrition-set.png",
            type: "general",
            achieved: "unachieved",
            dateAchieved: "null",
            description: "To feel well, you gotta eat well. First nutrition goal set",
        },
        twenty: {
            name: "10 Nutrition Goals Set",
            image: "/img/achievements/nutrition/set/10-nutrition-set.png",
            type: "nutrition",
            achieved: "unachieved",
            dateAchieved: "null",
            description: "10 nutrition goals set, now let's get them completed.",
        },
        twentyone: {
            name: "20 Nutrition Goals Set",
            image: "/img/achievements/nutrition/set/20-nutrition-set.png",
            type: "nutrition",
            achieved: "unachieved",
            dateAchieved: "null",
            description: "Holy smokes, 20 nutrition goals set, that must be some kinda record?",
        },
        twentytwo: {
            name: "First Nutrition Goal Completed",
            image: "/img/achievements/nutrition/complete/1-nutrition-complete.png",
            type: "nutrition",
            achieved: "unachieved",
            dateAchieved: "null",
            description: "Eating healthy isn't that difficult, you just proved it. First nutrition goal completed.",
        },
        twentythree: {
            name: "10 Nutrition Goals Completed",
            image: "/img/achievements/nutrition/complete/10-nutrition-complete.png",
            type: "nutrition",
            achieved: "unachieved",
            dateAchieved: "null",
            description: "10 nutrition goals completed. A new taste for completing goals it seems.",
        },
        twentyfour: {
            name: "20 Nutrition Goals Completed",
            image: "/img/achievements/nutrition/complete/20-nutrition-complete.png",
            type: "",
            achieved: "unachieved",
            dateAchieved: "null",
            description: "You've done it. 20 nutrition goals completed.",
        },
        twentyfive: {
            name: "You've Completed It",
            image: "/img/achievements/general/final-goal.png",
            type: "general",
            achieved: "unachieved",
            dateAchieved: "null",
            description: "Wow, you've completed every achievement. Major pat on the back. Don't stop here though, keep setting and completing goals like the legend you are.",
        },
    }

    return achievements;
}