exports.achieve = function(){

    /* All achieved. */
    const achievements = [
        {
            name: "First Goal Set",
            image: "/img/achievements/general/set/1-general-set.png",
            type: "general",
            achieved: "achieved",
            dateAchieved: "null",
            description: "You've set your first goal. 'A journey of a thousand miles begins with a single step.' - Laozi, legendary Chinese philosopher.",
        },
        {
            name: "10 Goals Set",
            image: "/img/achievements/general/set/10-general-set.png",
            type: "general",
            achieved: "achieved",
            dateAchieved: "null",
            description: "10 goals set, this is ",
        },
        {
            name: "20 Goals Set",
            image: "/img/achievements/general/set/20-general-set.png",
            type: "general",
            achieved: "achieved",
            dateAchieved: "null",
            description: "",
        },
        {
            name: "First Goal Complete",
            image: "/img/achievements/general/complete/1-general-complete.png",
            type: "general",
            achieved: "achieved",
            dateAchieved: "null",
            description: "",
        },
        {
            name: "10 Goals Completed",
            image: "/img/achievements/general/complete/10-general-complete.png",
            type: "general",
            achieved: "achieved",
            dateAchieved: "null",
            description: "",
        },
        {
            name: "20 Goals Completed",
            image: "/img/achievements/general/complete/20-general-complete.png",
            type: "general",
            achieved: "achieved",
            dateAchieved: "null",
            description: "",
        },
        {
            name: "First Fitness Goal Set",
            image: "/img/achievements/fitness/set/1-fitness-set.png",
            type: "fitness",
            achieved: "achieved",
            dateAchieved: "null",
            description: "",
        },
        {
            name: "10 Fitness Goals Set",
            image: "/img/achievements/fitness/set/10-fitness-set.png",
            type: "fitness",
            achieved: "achieved",
            dateAchieved: "null",
            description: "",
        },
        {
            name: "20 Fitness Goals Set",
            image: "/img/achievements/fitness/set/20-fitness-set.png",
            type: "fitness",
            achieved: "achieved",
            dateAchieved: "null",
            description: "",
        },
        {
            name: "First Fitness Goal Completed",
            image: "/img/achievements/fitness/complete/1-fitness-complete.png",
            type: "fitness",
            achieved: "achieved",
            dateAchieved: "null",
            description: "",
        },
        {
            name: "10 Fitness Goals Completed",
            image: "/img/achievements/fitness/complete/10-fitness-complete.png",
            type: "fitness",
            achieved: "achieved",
            dateAchieved: "null",
            description: "",
        },
        {
            name: "20 Fitness Goals Completed",
            image: "/img/achievements/fitness/complete/20-fitness-complete.png",
            type: "fitness",
            achieved: "achieved",
            dateAchieved: "null",
            description: "",
        },
        {
            name: "First Healthy-Living Goal Set",
            image: "/img/achievements/health/set/1-health-set.png",
            type: "healthy-living",
            achieved: "achieved",
            dateAchieved: "null",
            description: "",
        },
        {
            name: "10 Healthy-Living Goals Set",
            image: "/img/achievements/health/set/10-health-set.png",
            type: "healthy-living",
            achieved: "achieved",
            dateAchieved: "null",
            description: "",
        },
        {
            name: "20 Healthy Living Goals Set",
            image: "/img/achievements/health/set/10-health-set.png",
            type: "healthy-living",
            achieved: "achieved",
            dateAchieved: "null",
            description: "",
        },
        {
            name: "First Healthy-Living Goal Completed",
            image: "/img/achievements/health/complete/1-health-complete.png",
            type: "healthy-living",
            achieved: "achieved",
            dateAchieved: "null",
            description: "",
        },
        {
            name: "10 Healthy-Living Goals Completed",
            image: "/img/achievements/health/complete/10-health-complete.png",
            type: "healthy-living",
            achieved: "achieved",
            dateAchieved: "null",
            description: "",
        },
        {
            name: "20 Healthy-Living Goals Completed",
            image: "/img/achievements/health/complete/20-health-complete.png",
            type: "healthy-living",
            achieved: "achieved",
            dateAchieved: "null",
            description: "",
        },
        {
            name: "First Nutrition Goal Set",
            image: "/img/achievements/nutrition/set/1-nutrition-set.png",
            type: "general",
            achieved: "achieved",
            dateAchieved: "null",
            description: "",
        },
        {
            name: "10 Nutrition Goals Set",
            image: "/img/achievements/nutrition/set/10-nutrition-set.png",
            type: "nutrition",
            achieved: "achieved",
            dateAchieved: "null",
            description: "",
        },
        {
            name: "20 Nutrition Goals Set",
            image: "/img/achievements/nutrition/set/20-nutrition-set.png",
            type: "nutrition",
            achieved: "achieved",
            dateAchieved: "null",
            description: "",
        },
        {
            name: "First Nutrition Goal Completed",
            image: "/img/achievements/nutrition/complete/1-nutrition-complete.png",
            type: "nutrition",
            achieved: "achieved",
            dateAchieved: "null",
            description: "",
        },
        {
            name: "10 Nutrition Goals Completed",
            image: "/img/achievements/nutrition/complete/10-nutrition-complete.png",
            type: "nutrition",
            achieved: "achieved",
            dateAchieved: "null",
            description: "",
        },
        {
            name: "20 Nutrition Goals Completed",
            image: "/img/achievements/nutrition/complete/20-nutrition-complete.png",
            type: "",
            achieved: "achieved",
            dateAchieved: "null",
            description: "",
        },
        {
            name: "You've Completed It",
            image: "/img/achievements/general/final-goal.png",
            type: "general",
            achieved: "achieved",
            dateAchieved: "null",
            description: "",
        },
    ]
    
    /* All unachieved.
    const achievements = [
        {
            name: "First Goal Set",
            image: "/img/achievements/general/set/1-general-set.png",
            type: "general",
            achieved: "unachieved",
            dateAchieved: "null",
            description: "You've set your first goal. 'A journey of a thousand miles begins with a single step.' - Laozi, legendary Chinese philosopher.",
        },
        {
            name: "10 Goals Set",
            image: "/img/achievements/general/set/10-general-set.png",
            type: "general",
            achieved: "unachieved",
            dateAchieved: "null",
            description: "10 goals set, this is ",
        },
        {
            name: "20 Goals Set",
            image: "/img/achievements/general/set/20-general-set.png",
            type: "general",
            achieved: "unachieved",
            dateAchieved: "null",
            description: "",
        },
        {
            name: "First Goal Complete",
            image: "/img/achievements/general/complete/1-general-complete.png",
            type: "general",
            achieved: "unachieved",
            dateAchieved: "null",
            description: "",
        },
        {
            name: "10 Goals Completed",
            image: "/img/achievements/general/complete/10-general-complete.png",
            type: "general",
            achieved: "unachieved",
            dateAchieved: "null",
            description: "",
        },
        {
            name: "20 Goals Completed",
            image: "/img/achievements/general/complete/20-general-complete.png",
            type: "general",
            achieved: "unachieved",
            dateAchieved: "null",
            description: "",
        },
        {
            name: "First Fitness Goal Set",
            image: "/img/achievements/fitness/set/1-fitness-set.png",
            type: "fitness",
            achieved: "unachieved",
            dateAchieved: "null",
            description: "",
        },
        {
            name: "10 Fitness Goals Set",
            image: "/img/achievements/fitness/set/10-fitness-set.png",
            type: "fitness",
            achieved: "unachieved",
            dateAchieved: "null",
            description: "",
        },
        {
            name: "20 Fitness Goals Set",
            image: "/img/achievements/fitness/set/20-fitness-set.png",
            type: "fitness",
            achieved: "unachieved",
            dateAchieved: "null",
            description: "",
        },
        {
            name: "First Fitness Goal Completed",
            image: "/img/achievements/fitness/complete/1-fitness-complete.png",
            type: "fitness",
            achieved: "unachieved",
            dateAchieved: "null",
            description: "",
        },
        {
            name: "10 Fitness Goals Completed",
            image: "/img/achievements/fitness/complete/10-fitness-complete.png",
            type: "fitness",
            achieved: "unachieved",
            dateAchieved: "null",
            description: "",
        },
        {
            name: "20 Fitness Goals Completed",
            image: "/img/achievements/fitness/complete/20-fitness-complete.png",
            type: "fitness",
            achieved: "unachieved",
            dateAchieved: "null",
            description: "",
        },
        {
            name: "First Healthy-Living Goal Set",
            image: "/img/achievements/health/set/1-health-set.png",
            type: "healthy-living",
            achieved: "unachieved",
            dateAchieved: "null",
            description: "",
        },
        {
            name: "10 Healthy-Living Goals Set",
            image: "/img/achievements/health/set/10-health-set.png",
            type: "healthy-living",
            achieved: "unachieved",
            dateAchieved: "null",
            description: "",
        },
        {
            name: "20 Healthy Living Goals Set",
            image: "/img/achievements/health/set/10-health-set.png",
            type: "healthy-living",
            achieved: "unachieved",
            dateAchieved: "null",
            description: "",
        },
        {
            name: "First Healthy-Living Goal Completed",
            image: "/img/achievements/health/complete/1-health-complete.png",
            type: "healthy-living",
            achieved: "unachieved",
            dateAchieved: "null",
            description: "",
        },
        {
            name: "10 Healthy-Living Goals Completed",
            image: "/img/achievements/health/complete/10-health-complete.png",
            type: "healthy-living",
            achieved: "unachieved",
            dateAchieved: "null",
            description: "",
        },
        {
            name: "20 Healthy-Living Goals Completed",
            image: "/img/achievements/health/complete/20-health-complete.png",
            type: "healthy-living",
            achieved: "unachieved",
            dateAchieved: "null",
            description: "",
        },
        {
            name: "First Nutrition Goal Set",
            image: "/img/achievements/nutrition/set/1-nutrition-set.png",
            type: "general",
            achieved: "unachieved",
            dateAchieved: "null",
            description: "",
        },
        {
            name: "10 Nutrition Goals Set",
            image: "/img/achievements/nutrition/set/10-nutrition-set.png",
            type: "nutrition",
            achieved: "unachieved",
            dateAchieved: "null",
            description: "",
        },
        {
            name: "20 Nutrition Goals Set",
            image: "/img/achievements/nutrition/set/20-nutrition-set.png",
            type: "nutrition",
            achieved: "unachieved",
            dateAchieved: "null",
            description: "",
        },
        {
            name: "First Nutrition Goal Completed",
            image: "/img/achievements/nutrition/complete/1-nutrition-complete.png",
            type: "nutrition",
            achieved: "unachieved",
            dateAchieved: "null",
            description: "",
        },
        {
            name: "10 Nutrition Goals Completed",
            image: "/img/achievements/nutrition/complete/10-nutrition-complete.png",
            type: "nutrition",
            achieved: "unachieved",
            dateAchieved: "null",
            description: "",
        },
        {
            name: "20 Nutrition Goals Completed",
            image: "/img/achievements/nutrition/complete/20-nutrition-complete.png",
            type: "",
            achieved: "unachieved",
            dateAchieved: "null",
            description: "",
        },
        {
            name: "You've Completed It",
            image: "/img/achievements/general/final-goal.png",
            type: "general",
            achieved: "unachieved",
            dateAchieved: "null",
            description: "",
        },
    ]*/
    return achievements;
}